### ISSUE TITLE
UI Revamp

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/shl-trading-cards#134]
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/135
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/136
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/137
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/139
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/138
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/140
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/141
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/208
- [ ] https://github.com/GuthrieW/shl-trading-cards/issues/142
