### ISSUE TITLE
Add Trade Hub

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/shl-trading-cards#18]
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/97
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/98
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/99
- [x] https://github.com/GuthrieW/shl-trading-cards/issues/100

**Comment by GuthrieW** [comment]
![image](https://user-images.githubusercontent.com/18729387/212500500-ad2e0883-2420-4622-a42c-541efaef820c.png)

![image](https://user-images.githubusercontent.com/18729387/212500508-94b4cd6f-ca27-4a05-a18c-e8d4e76a7cea.png)

**Comment by GuthrieW** [comment]
https://github.com/GuthrieW/shl-trading-cards/pull/101
